<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KPT</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
    <LangVersion>5</LangVersion>
    <ResolveAssemblyWarnOrErrorOnTargetMismatches>None</ResolveAssemblyWarnOrErrorOnTargetMismatches>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="RhinoCommon" Version="5.1.30000.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>$(MSBuildProjectDirectory)/lib/RhinoCommon.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="itextsharp">
      <HintPath>$(MSBuildProjectDirectory)/lib/itextsharp.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
</Project>